config/routes.rb
Paporeto::Application.routes.draw do
  devise_for :users
  resources :categories, except: :show
  
  resources :articles
  resources :users, except: :show

  root 'articles#index'
end 

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :category

  validates :title, :category, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles
  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /articles
  def index
    @articles = Article.all
  end

  # GET /articles/1
  def show
    @articles = Article.order(published_at: :desc).order(:title)
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article, notice: 'Artigo salvo.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /articles/1
  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Artigo atualizado com sucesso.'
    else
      render :edit
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    redirect_to articles_url, notice: 'Artigo excluído.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def article_params
      params.require(:article).permit(:title, :body, :published_at, :category_id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /categories
  def index
    @categories = Category.all
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_url
    else
      render :new
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to categories_url
    else
      render :edit
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_url
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /users/1
  def update
    if user_params[:password].blank?
      @user.update_without_password(user_params_without_password)
    else
      @user.update(user_params)
    end

    if @user.valid?
      redirect_to users_url
    else
      render action: 'edit'
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'Usuário Excluido.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def user_params_without_password
      user_params.delete(:password)
      user_params.delete(:password_confirmation)
      user_params
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def time_to_read(text)
    time = text.split.size / 180.0
    distance_of_time_in_words(time.minutes)
  end

  def nav_status(controller)
    if params[:controller] == controller
      'active'
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.slim
h1 Editar Artigo

== render 'shared/form'

app/views/articles/index.html.slim
h1 Artigos
 
table.table.table-striped
  thead
    tr
      th Título
      th Publicado em
      th Categoria
      th
 
  tbody
    - @articles.each do |article|
      tr
        td = article.title
        td = l article.published_at
        td = article.category.name
        td
          .btn-group.pull-right
             = link_to 'Ver', article, class: 'btn btn-default btn-sm'
             = link_to 'Editar', edit_article_path(article), class: 'btn btn-default btn-sm'
             = link_to 'Excluir', article, :confirm => 'Tem certeza?', method: :delete, class: 'btn btn-default btn-sm'
 
br
 
= link_to 'Criar Artigo', new_article_path, class: 'btn btn-primary'

app/views/articles/new.html.slim
h1 Novo Artigo

== render 'shared/form'

app/views/articles/shared/_form.html.slim
= simple_form_for(@article) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.association :category, prompt: 'Selecione'
    = f.input :body
    = f.input :published_at

  .form-actions
    = f.button :submit, class: 'btn btn-primary'

app/views/articles/show.html.slim
-if notice
  .alert.alert-info.alert-dismissable
    button type="button" class="close" data-dismiss="alert" aria-hidden="true" &times; 
    = notice
 
h1 
  = @article.title
  .pull-right
    = link_to 'Editar', edit_article_path(@article), class: 'btn btn-default'
 
hr

strong = @article.category.name
.pull-right Cerca de <b>#{time_to_read @article.body}</b> de leitura

p = l @article.published_at
= simple_format @article.body

app/views/categories/edit.html.slim
h1 Editar Categoria

== render 'form'

app/views/categories/index.html.slim
h1 Categorias

table.table.table-striped
  thead
    tr
      th Name
      th

  tbody
    - @categories.each do |category|
      tr
        td = category.name
        td
          .btn-group.pull-right
            = link_to 'Editar', edit_category_path(category), class: 'btn btn-default btn-sm'
            = link_to 'Excluir', category, data: {:confirm => 'Are you sure?'}, :method => :delete, class: 'btn btn-default btn-sm'

br

= link_to 'Nova Categoria', new_category_path, class: 'btn btn-primary'

app/views/categories/new.html.slim
h1 Nova Categoria

== render 'shared/form'

app/views/categories/shared/_form.html.slim
= simple_form_for(@category) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit, class: 'btn btn-primary'

app/views/layouts/application.html.slim
doctype html
html
  head
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title Paporeto
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = csrf_meta_tags
 
    /[if lt IE 9]
      = javascript_include_tag "html5shiv", "data-turbolinks-track" => true
      = javascript_include_tag "respond.min", "data-turbolinks-track" => true
  body
    - if user_signed_in?
      .navbar.navbar-inverse.navbar-fixed-top
       .container
         .navbar-header
            = link_to 'Blog', root_path, class: 'navbar-brand'
         .navbar-collapse
           ul.nav.navbar-nav
             li class="#{nav_status('articles')}" = link_to 'Artigos', articles_path
             li class="#{nav_status('categories')}" = link_to 'Categorias', categories_path
             li class="#{nav_status('users')}" = link_to 'Usuários', users_path
           ul.nav.navbar-nav.pull-right
             li = link_to current_user.name, edit_user_path(current_user)
             li = link_to 'Sair', destroy_user_session_path, method: :delete
   
    .container
      = yield
    = javascript_include_tag "application", "data-turbolinks-track" => true

app/views/users/_form.html.slim
= simple_form_for(@user) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :email
    = f.input :password
    = f.input :password_confirmation

  .form-actions
    = f.button :submit, class: 'btn btn-primary'

app/views/users/edit.html.slim
h1 Editar Usuário

== render 'form'

app/views/users/index.html.slim
h1 Usuários

table.table.table-striped
  thead
    tr
      th Nome
      th Email
      th

  tbody
    - @users.each do |user|
      tr
        td = user.name
        td = user.email
        td

          .btn-group.pull-right 
            = link_to 'Editar', edit_user_path(user), class: 'btn btn-default btn-sm'
            = link_to 'Excluir', user, data: {:confirm => 'Tem certeza?'}, :method => :delete, class: 'btn btn-default btn-sm'

br

= link_to 'Criar Usuário', new_user_path, class: 'btn btn-primary'

app/views/users/new.html.slim
h1 Criar Usuário

== render 'form'